### ISSUE TITLE
Problems when all fields are selected in a Join

### ISSUE THREAD

**Issue by JuanLuisNL** [isoos/postgresql-dart#269]
"SELECT emp.id, emp.name,  deleg.* AS deleg 
FROM empresas emp
LEFT JOIN delegaciones deleg ON deleg.id_empresa = emp.id"

In a query of this type the alias is lost. I think it should be like this: 
"deleg__id, deleg__name, deleg__vat", etc.
However, there is only the name of the field: "id, name, vat"

Thank you!

**Comment by isoos** [comment]
I'm still unsure whether Postgres supports `SELECT deleg.* AS deleg ...`. Have you seen somewhere that it should work like you expect it to work?

**Comment by isoos** [comment]
E.g. if you enter the same query in the `psql` client, do you have the column names as you expect?

**Comment by JuanLuisNL** [comment]
Hello, no, it only returns the name of the field, however, in the previous version of your package a map was created with each table, I understand that it was changed to support several Joins of the same table, it is important. But couldn't you, for example, put the table name as part of the field name ("delegaciones__id, delegaciones__name")? I have seen that in "toColumnMap" there is "tableOid", or in another way, put that id= "175885__id, 175885_name".
Thank you

**Comment by isoos** [comment]
> only returns the name of the field

That's the Postgresql behavior, we do not take away from it, and with the v3 release, we want to keep it that way - being close to whatever the default Postgresql behavior is.

>  the previous version of your package a map was created with each table, I understand that it was changed to support several Joins of the same table, it is important

It was taken out, because the table name OID cache made the query logic unnecessarily complex, and unreliable in some edge cases. The result object still has a `schema` property that has the table/view OIDs, and if you wanted to, you can write your own query logic for resolving those OIDs to names. We have decided that this feature should not be automatic (may run queries non-deterministically), and if there is a need for it, we may host a utility class for that, but not as part of the main API.

> But couldn't you, for example, put the table name as part of the field name

That is another reason why we shouldn't do it: this is an opinionated transformation. Supporting arbitrary ways of defining output column name patterns is outside of the scope of this package. You may add a custom layer on top of the basic API to (a) generate large queries based on your requirements and (b) interpret its output in whatever way you want.

**Comment by JuanLuisNL** [comment]
Thank you very much for your kind answers. I will opt for what you say. I will adapt "toColumnMap" to my needs. Regards

**Comment by isoos** [comment]
@JuanLuisNL: You could also consider generating the part where the query has `deleg.* as deleg`. E.g. instead of that, the generated code writes `deleg.a as deleg__a, deleg.b as deleg__b`.

**Comment by JuanLuisNL** [comment]
We are transforming a huge ERP from .NET to flutter and the tables are up to 200 fields, in some cases it would be complicated what you say. Adapting "toColumMap" works fine for me.
The application with your package is working great!

There are many fields on each tab:
![image](https://github.com/isoos/postgresql-dart/assets/89520605/b64c9bf1-3a75-415c-bcf3-37c721d09606)

Thank you very much for everything!

**Comment by isoos** [comment]
@JuanLuisNL: looks good, good luck! Closing this issue now, feel free to open a new one if there is any annoying behavior with the package.

**Comment by JuanLuisNL** [comment]
Thank you very much
