### ISSUE TITLE
this package dont working in flutter !

### ISSUE THREAD

**Issue by abduraimovdev** [isoos/postgresql-dart#334]
this package dont working in flutter !

**Comment by isoos** [comment]
First, please note that it is not recommended that you store database credentials in a mobile app. Your database will get compromised.

Second, to connect to a postgres database from android, you need extra permissions: https://developer.android.com/develop/connectivity/network-ops/connecting
I don't know the details, but I imagine you may need similar thing for ios apps too.

Lastly, please provide details in any bug report, otherwise nobody will be able to help you.
