### ISSUE TITLE
Different way to handle rollback on failed query within a transaction

### ISSUE THREAD

**Issue by davidmartos96** [isoos/postgresql-dart#85]
Hello!
I have a transaction that takes a long time because lots of data is being inserted.
After this data is all sent to postgres, there are a few ALTER TABLEs that I need to execute to finish the transaction.
The problem is that this ALTER TABLE could take a long time to obtain the lock, so this can lock the production database if there is some traffic.
What I would like to do is use a SAVEPOINT after the data is uploaded, while still being in the transaction, and have a lock_timeout with a few seconds. If the lock cannot be obtained, the ALTER TABLE is retried until succeed and a ROLLBACK SAVEPOINT is executed so that we don't have to wait a long time again to upload that data again.

The problem I'm encountering is that the library will cancel the transaction when an error is encountered, even if this is expected to happen and the application can handle this situation.

Would there be any way to achieve this? Or would it be in the scope of the V3 rewrite?

On another note I have a separate question, and this is just for curiosity. Where in the source code does the library manages to not run a second transaction while another one is executing with the same connection? I'm not able to find it.

**Comment by isoos** [comment]
IIRC postgres server limits us in that regard: one connection may have only one transaction. A `Connection` object backs a single TCP connection to the server, so you can (or rather should) only run one transaction at a time on it.

**Comment by davidmartos96** [comment]
That's good to know. Thank you!

**Comment by insinfo** [comment]
@davidmartos96
I don't know if my experience can contribute here, but I was facing serious performance problems in a production application because of transactions, basically when a transaction was taking place this prevented some users from using the application, I ended up using a connection pool and multiple instances using angel3_production multi-threads, but the problem persisted as there was no way for me to maintain so many instances and sufficient connections due to memory and CPU limitations of the database server, the new application aimed to replace the original one made in PHP 5.3 very old, the new application was built to replace the old one for reasons of security, maintainability, compatibility with modern browsers, and performance, but initially the new and old application ran side by side to allow a smooth migration, and even though the old one was original application had a much better performance than the new one made in Dart (Angel3, Eloquent, AngularDart 7), that's when I restructured the application to no longer maintain open connections with the database, I removed the pool and started opening a connection for each request together with a file cache implementation (json) for some routes and now the application is 20x faster

**Comment by davidmartos96** [comment]
@insinfo Thanks for the insight.
How does that json cache work? What gets serialized as json?

**Comment by insinfo** [comment]
It's a very simple file cache implementation, basically every time a request arrives in the get "/products/:id" and getAll "/products" method in the backend controller layer I check if there is already this item in the cache file and If the file's creation date has not exceeded my cutoff date, if it is already in the cache, it responds to the frontend with the cache content (json file), if it is not in the cache, then it opens a connection to the database and obtains the content and updates the cache and responds to the frontend, the cutoff date and according to each use case, trimming some endpoints 2 to 30 minutes for others is 4 months with the file being deleted if the data undergoes changes (Update/Delete )


##### a pseudocode would be something like this

```dart
import 'dart:convert';
import 'dart:io';
import 'package:crypto/crypto.dart';

class JsonFileCache {
  final String cacheKey;
  final String cacheDirPath;
  final Duration cacheDuration;

  DateTime get _now => DateTime.now();
  File get _cacheFile => File(cacheDirPath + '/'+_generateMd5(cacheKey)+'.json');

  String _generateMd5(String input) {
    final bytes = utf8.encode(input); 
    final md5Result = md5.convert(bytes); 
    return md5Result.toString();
  }

  JsonFileCache(this.cacheKey,
      {this.cacheDuration = const Duration(minutes: 30),this.cacheDirPath ='/tmp'});

  Future<bool> isValid() async {
    if (await _cacheFile.exists()) {
      final lastModified = await _cacheFile.lastModified();
      return _now.difference(lastModified) < cacheDuration;
    }
    return false;
  }

  Future<Map<String, dynamic>> read() async {
    if (await _cacheFile.exists()) {
      final contents = await _cacheFile.readAsString();
      return json.decode(contents);
    }
    return {};
  }
  Future<String> readAsJson() async {
    return jsonEncode(await read());
  }


  Future<void> write(Map<String, dynamic> data) async {
    await _cacheFile.writeAsString(json.encode(data));
  }
}

// Example usage:
class ProductsController {
 static Future<dynamic> getAll(request,response) async {
    final cache = JsonFileCache(request.path);
    final db = Conection('....');
    try{
    if (await cache.isValid()) {
      // Use cached data
      final cachedData = await cache.readAsJson();
      print('Using cached data: $cachedData');
     return response.json(cachedData);
    } else {
      // Fetch data from database      
      await  db.open();
      final data = await db.query('sql...').asJson();
      await  db.close();
      // Save the data to the cache
      await cache.write(data);
      print('Fetched data from API: $data');
      return  response.json(data);      
    }
    }catch(e,s){
       await db.close();
       return  response.json({'error':'..'}); 
    }
  }
}


final app = Angel();
//routes
app.get('/products',ProductsController.getAll);
```

**Comment by isoos** [comment]
Closing as I don't see any immediate action here. Please reopen (a new issue) if you think the v3 API is still lacking.
