### ISSUE TITLE
Cannot infer query parameter types in VALUES statement.

### ISSUE THREAD

**Issue by schultek** [isoos/postgresql-dart#89]
I have an unexpected error with the following query:

```dart
var result = await db.query('SELECT * FROM ( VALUES ( @id:int4 ) ) AS test', substitutionValues: {'id': 2});
```

The error:
`PostgreSQLSeverity.error : Specified parameter types do not match column parameter types in query SELECT * FROM ( VALUES ( @id:int4 ) ) AS test`

It seems like the database won't correctly infer the column type of the `VALUES` statement, even though I have set an explicit parameter type.

Changing it to the following works: (double `::`)
```dart
var result = await db.query('SELECT * FROM ( VALUES ( @id::int4 ) ) AS test', substitutionValues: {'id': 2});
```

However judging from the implementation, this then sends the parameter as text encoded (not not the more efficient binary form) and casts it on the database back to the correct type.

The postgres docs state:
> When VALUES is used in INSERT, the values are all automatically coerced to the data type of the corresponding destination column. When it's used in other contexts, it might be necessary to specify the correct data type. If the entries are all quoted literal constants, coercing the first is sufficient to determine the assumed type for all:
> ```
> SELECT * FROM machines
> WHERE ip_address IN (VALUES('192.168.0.1'::inet), ('192.168.0.10'), ('192.168.1.43')); 
> ```

---

This is maybe not even solvable by this package, I just wanted to open this to see if you have some more insights on this. My solution right now would be to do this:

```dart
var result = await db.query('SELECT * FROM ( VALUES ( @id:int4::int4 ) ) AS test', substitutionValues: {'id': 2});
```

Meaning it's both specifying the parameter type and the cast.

**Comment by ibotva** [comment]
Hey check out 8.1.1 of the [Postgres Docs](https://www.postgresql.org/docs/current/datatype-numeric.html), typical type conventions are `integer` or `int`, `smallint` and `bigint`. I do see mention of `int2`, `int4` and `int8`, but as I looked into Darts type conventions, the `int4` property is sealed. I would recommend using `smallint` for your table instead of using extensions. Why are you trying to use a specific size of integer in dart if you don't mind my asking?

I am working on a PR for a few issues right now though, so if you happen to be working on this already and know a possible solution I'll add it.

**Comment by isoos** [comment]
I believe the v3 query processing can infer these correctly.
