### ISSUE TITLE
Cannot throw custom exceptions in response to PostgreSQLException within transaction

### ISSUE THREAD

**Issue by bryanoltman** [isoos/postgresql-dart#95]
Exceptions thrown in response to a `PostgreSQLException` in a transaction block are not propagated out. Instead, `transaction` throws the original `PostgreSQLException`.

A test that demonstrates this issue:

```dart
    test('exception thrown in transaction is propagated out', () async {
      final expectedException = Exception('my custom exception');
      dynamic actualException;
      await conn.transaction((c) async {
        await c.query('INSERT INTO t (id) VALUES (1)');
        try {
          await c.query('INSERT INTO t (id) VALUES (1)');
        } on PostgreSQLException catch (_) {
          throw expectedException;
        }
      }).catchError((error) => actualException = error);

      // Fails, this is actually the original PostgreSQLException
      expect(actualException, expectedException);
    });
```

This code is on a branch at https://github.com/bryanoltman/postgresql-dart/blob/custom-error/test/transaction_test.dart#L652-L665.

**Comment by bryanoltman** [comment]
The current workaround for this is to catch the `PostgreSQLException` outside of the transaction block and throw the custom exception there. It would be nicer to catch the exception closer to where it occurs, but this issue is not a blocker in any sense of the word.

**Comment by isoos** [comment]
This line will take the precedence of a query exception over the exception coming from the transaction execution block:
https://github.com/isoos/postgresql-dart/blob/master/lib/src/transaction_proxy.dart#L124

I think it makes more sense to remove this than keep the behavior: if the query is not in a try-catch block, the exception will naturally bubble up to the transaction and will get set, otherwise the author is already prepared for the exception and should be able to handle it.
